spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/oauth2
        username: root
        password:
        initialization-mode: never
    jpa:
      hibernate:
        ddl-auto: none


# --- server
server:
  port: 8083


security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8082/oauth/token
      userAuthorizationUri: https://localhost:8082/oauth/authorize



